#include <stdio.h>

int main()
{
	int n;
	scanf("%d",&n);
	char str[n+1];
	scanf("%s",str);
    int arr[5][3*n+n-1];
    int count=0;
    for(int w=0;w<n;w++)
    {
    	switch((int)(str[w]-'0'))
    	{
    		case 0:
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=0;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    		    break;
    		case 1:
    			arr[0][count]=0;
    			arr[1][count]=0;
    			arr[2][count]=0;
    			arr[3][count]=0;
    			arr[4][count]=0;
    			count++;
    			arr[0][count]=0;
    			arr[1][count]=0;
    			arr[2][count]=0;
    			arr[3][count]=0;
    			arr[4][count]=0;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    		    break;
    		case 2:
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
                arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    		    break;
    		case 3:
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    		    break;
    		case 4:
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=0;
    			count++;
    			arr[0][count]=0;
    			arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=0;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    		    break;
    		case 5:
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
                arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    		    break;    
    		case 6:
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    		    break;
    		case 7:
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=0;
    			arr[3][count]=0;
    			arr[4][count]=0;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=0;
    			arr[3][count]=0;
    			arr[4][count]=0;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    		    break;
    		case 8:
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
                arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    		    break;
    		case 9:
    			arr[0][count]=1;
    			arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
    			arr[1][count]=0;
    			arr[2][count]=1;
    			arr[3][count]=0;
    			arr[4][count]=1;
    			count++;
    			arr[0][count]=1;
                arr[1][count]=1;
    			arr[2][count]=1;
    			arr[3][count]=1;
    			arr[4][count]=1;
    			count++;
    		    break;
		}
		if(count==(3*n+n-1))
		    break;
		arr[0][count]=0;
    	arr[1][count]=0;
    	arr[2][count]=0;
    	arr[3][count]=0;
    	arr[4][count]=0;
    	count++;
	}
	for(int i=0;i<5;i++)
	{
		for(int w=0;w<count;w++)
		{
			if(arr[i][w]==1)
			printf("X");
			else
			printf(".");
		}
		printf("\n");
	}
    
	return 0;
}